root = "."
tmp_dir = "./tmp"

[build]
cmd = "go build -o ./tmp/faucet ."
# Binary file yields from `cmd`.
bin = "tmp/faucet"
# Watch these filename extensions.
include_ext = ["go", "tpl", "html"]
exclude_dir = ["web/ng/node_modules"]
# Exclude unchanged files.
exclude_unchanged = true
# This log file places in your tmp_dir.
log = "air.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = false
# Delay after sending Interrupt signal
kill_delay = 500

[log]

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
