name: Go

on:
  push:
    branches: [ master ]
    paths:
      - 'prysmbot/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'prysmbot/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        working-directory: prysmbot
        run: go mod download && go build -v ./...

      - name: Test
        working-directory: prysmbot
        run: go test -v ./...