# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
      - 'web/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        working-directory: web/ng-boilerplate
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        working-directory: web/ng-boilerplate
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci and npm run build:dev
        working-directory: web/ng-boilerplate
        run: |
          npm ci
          npm run build:ci

      - name: npm run lint
        working-directory: web/ng-boilerplate
        run: |
          npm run lint
